### ISSUE TITLE
errors when running demo

### ISSUE THREAD

**Issue by lonelyatu** [LLNL/LEAP#13]
I have installed the leapct, but the errors encounter when I run the demo as below:
![image](https://github.com/LLNL/LEAP/assets/18749863/08a881dc-fb84-4508-b5cc-420cd88e3d6c)

Can you help me with this issue?

**Comment by kylechampley** [comment]
The install probably did not complete successfully because it cannot find libleap.so which is the LEAP compiled dynamic library.  Please run the following command:
pip install -v .

This print a message of why it did not compile.  Send me this text if you need further help.

**Comment by lonelyatu** [comment]
Maybe the visual studio Version is not right. I use the VS 2022 to compile the leapct and I will use vs 2019 to re-compile this project.

**Comment by kylechampley** [comment]
Ya, that could be it.  The newest versions of VS do not always support CUDA, so that is why we suggest 2019.

**Comment by kylechampley** [comment]
Could you pull the latest code and try again?  I made changes to the pip install script, setup.py.  I think the setup routine was not copying the dynamic library for Windows.

Sorry I did not catch this earlier.  I don't use the pip install because I need to make constant changes and thus I did not see that it was not working.

**Comment by JoosenLi** [comment]
> The install probably did not complete successfully because it cannot find libleap.so which is the LEAP compiled dynamic library. Please run the following command: pip install -v .
> 
> This print a message of why it did not compile. Send me this text if you need further help.

I‘m encountering the same error as @lonelyatu , and it persists even after installing the latest version (the setup.py version was updated 15 hours ago). When I run ‘pip install -v’, the version returned is ‘Using pip 23.3.2 from /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages/pip (python 3.9)’. Can you help me solve these problems?

**Comment by kylechampley** [comment]
I think you forgot to add the "dot".  The command should be:
pip install -v .

Do this and then send me the output.

**Comment by JoosenLi** [comment]
> I think you forgot to add the "dot". The command should be: pip install -v .
> 
> Do this and then send me the output.

the outputs are as follow：

pip install -v .
Using pip 23.3.2 from /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Processing /data4/liqiaoxin/code/LEAP-main
  Running command python setup.py egg_info
  ./etc/build.sh: 13: cmake: not found
  /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
  !!

          ********************************************************************************
          Usage of dash-separated 'description-file' will not be supported in future
          versions. Please use the underscore name 'description_file' instead.

          By 2024-Sep-26, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    opt = self.warn_dash_deprecation(opt, section)
  running egg_info
  creating /tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info
  writing /tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-pip-egg-info-qfon70i9/leapct.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from leapct==0.99) (1.26.2)
Requirement already satisfied: torch in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from leapct==0.99) (2.1.2)
Requirement already satisfied: filelock in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (3.13.1)
Requirement already satisfied: typing-extensions in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (4.9.0)
Requirement already satisfied: sympy in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (1.12)
Requirement already satisfied: networkx in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (3.2.1)
Requirement already satisfied: jinja2 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (3.1.2)
Requirement already satisfied: fsspec in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (2023.12.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (12.1.105)
Requirement already satisfied: triton==2.1.0 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from torch->leapct==0.99) (2.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->leapct==0.99) (12.3.101)
Requirement already satisfied: MarkupSafe>=2.0 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from jinja2->torch->leapct==0.99) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages (from sympy->torch->leapct==0.99) (1.3.0)
Building wheels for collected packages: leapct
  Running command python setup.py bdist_wheel
  ./etc/build.sh: 13: cmake: not found
  /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
  !!

          ********************************************************************************
          Usage of dash-separated 'description-file' will not be supported in future
          versions. Please use the underscore name 'description_file' instead.

          By 2024-Sep-26, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    opt = self.warn_dash_deprecation(opt, section)
  running bdist_wheel
  running build
  running build_py
  creating build/lib
  copying src/leaptorch.py -> build/lib
  copying src/leapctype.py -> build/lib
  /home/liqiaoxin/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!

          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.

          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************

  !!
    self.initialize_options()
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  copying build/lib/leaptorch.py -> build/bdist.linux-x86_64/wheel
  copying build/lib/leapctype.py -> build/bdist.linux-x86_64/wheel
  running install_egg_info
  running egg_info
  writing src/leapct.egg-info/PKG-INFO
  writing dependency_links to src/leapct.egg-info/dependency_links.txt
  writing requirements to src/leapct.egg-info/requires.txt
  writing top-level names to src/leapct.egg-info/top_level.txt
  reading manifest file 'src/leapct.egg-info/SOURCES.txt'
  writing manifest file 'src/leapct.egg-info/SOURCES.txt'
  Copying src/leapct.egg-info to build/bdist.linux-x86_64/wheel/leapct-0.99-py3.9.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/leapct-0.99.dist-info/WHEEL
  creating '/tmp/pip-wheel-tbcjr9xr/leapct-0.99-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'leapctype.py'
  adding 'leaptorch.py'
  adding 'leapct-0.99.dist-info/METADATA'
  adding 'leapct-0.99.dist-info/WHEEL'
  adding 'leapct-0.99.dist-info/top_level.txt'
  adding 'leapct-0.99.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for leapct (setup.py) ... done
  Created wheel for leapct: filename=leapct-0.99-py3-none-any.whl size=27111 sha256=7f7128bdef8c07cfd40dd288bc13cb39a8f74b93d3df9885383fc4d5e3d75d3d
  Stored in directory: /data4/liqiaoxin/.cache/pip/wheels/7d/1d/94/4df1ba5b11c10424179467f3cfcc967f1ccd00c93433c90412
Successfully built leapct
Installing collected packages: leapct
Successfully installed leapct-0.99

**Comment by kylechampley** [comment]
Yep, I see the issue.  You either don't have CMake installed or your system cannot find it.  Look at around line 5 where it says:
./etc/build.sh: 13: cmake: not found

Note that the list of dependencies are here: https://github.com/LLNL/LEAP/wiki/Installing-and-Using-LEAP

**Comment by lonelyatu** [comment]
I am so sorry that I have used the updated files and VS2019 to compile the project. But I don't know why the cmake (version 3.28.1) can't find the VS compilers as reported below:
![image](https://github.com/LLNL/LEAP/assets/18749863/2f0766e8-371d-4d76-9c00-5f33f8eb0680)
Can you provide another way to compile this package?

**Comment by kylechampley** [comment]
Try using the build script.  Like this:
cd LEAP
.\etc\win_build.bat

**Comment by lonelyatu** [comment]
The same problem occurs.

**Comment by kylechampley** [comment]
What version of cmake do you have?  Make sure it is at least version 3.0.

**Comment by lonelyatu** [comment]
cmake version is 3.28.1

**Comment by kylechampley** [comment]
When you install VS, did you check the box that says "Desktop development with C++"?

**Comment by lonelyatu** [comment]
Yes.

**Comment by kylechampley** [comment]
Try running the VS installer again and look for a check box that says something like "Visual C++ tools for CMake".

**Comment by lonelyatu** [comment]
OK. I will try again.

**Comment by kylechampley** [comment]
Good luck.  I hope you figure it out.  In case you cannot, I just released the first version of LEAP and included pre-compiled libraries in the release which you can download.  You can find this here: 
https://github.com/LLNL/LEAP/releases

**Comment by lonelyatu** [comment]
Bad news is I still cannot compile the project. Good news is your released .dll file works perfectly. I'm really very grateful to you!!!
