### ISSUE TITLE
Help me: Offsetscan

### ISSUE THREAD

**Issue by ProjX0** [LLNL/LEAP#35]
Thank you for sharing the excellent  toolkit.

I am currently interested in offset scan and am trying it with the data I have. However, I seem to have made a mistake, and the reconstruction isn’t working well.

Could you possibly help me if I share the geometry information and data with you?

Thank you very much.

**Comment by kylechampley** [comment]
Sure.  Please also send a picture of one of the projections.

**Comment by hws203** [comment]
I guess that your right_side offscan mechanism has some issue. I tested your "d23_offscan.py" which shows some strange reconed slice and like attached one. I just change the +100 offset by -100 as like centerCols = 0.5*(numCols-1)-100
Please, check it by just changing the offset value by -100.
![Uploading right_offscan.PNG…]()

**Comment by ProjX0** [comment]
https://osstem.box.com/s/odjfsa36hoytoq6ky9t49ndneswhm0xn

I am pleased to share the data link with you. The actual acquisition spans from 0044.raw to 0752.raw, covering a rotation range of 360 degrees. The geometry.txt file includes essential parameters for each frame, such as SOD and SDD.

Here are the offset parameters I have set:

numRows = 1628
numCols = 1500
pixelSize = 0.098 mm 
shift_distance = 38.139 mm
centerRow = 0.5 * (numRows - 1) - (shift_distance / pixelSize)
centerCol = 0.5 * (numCols - 1) - (shift_distance / pixelSize)

Given the size of the data, I occasionally encounter CUDA memory outages. To mitigate this, I am currently testing using a 1/2 bin mode.

Please let me know if there is anything unusual or if there are specific aspects you would like me to be aware of.

Thank you very much.

**Comment by ProjX0** [comment]
![2024-05-14 09;33;24](https://github.com/LLNL/LEAP/assets/78583623/d67cafbc-5d4c-43e4-b4eb-2eeaa0a922fd)

For reference, the images are expected to look a certain way after reconstruction. I am currently trying to achieve this using LEAP, but it appears that I am making some mistakes, as the images are not coming out as intended.

![image](https://github.com/LLNL/LEAP/assets/78583623/0e3ed591-b653-4ee6-be0c-7baf6b4c1b5e)

**Comment by kylechampley** [comment]
Thank you @hws203 for pointing out that bug.  The cause for this was quite minor and was easy to fix.  Currently the bug fix is in my development branch [champley_dev](https://github.com/LLNL/LEAP/tree/champley_dev).  This branch will be merged into the main branch and a new LEAP release will come out later this week.  You can either use this new code now or there is a workaround if you want to just work with the current version.  The work-around is just add the following command after you set the reconstruction volume parameters:
leapct.set_diameterFOV(leapct.get_voxelWidth()*leapct.get_numX())
The issue you noticed was caused by LEAP calculating the field of view incorrectly.  Thus the above line forces LEAP to not restrict the field of view, so you can see the whole thing.

OK, now for @ProjX0 specific issue.  Could you post your whole LEAP script?  Above you have only shown a portion of it.  One question I have is where the "shift_distance" value came from.  I did not see this in the geometry file you posted.  Also, why do you shift centerCol and centerRow by this same amount?  I also don't understand the parameter names in that file like p0.x, p0.y, phi, etc.  Can you explain what these mean?

**Comment by ProjX0** [comment]
In our half-beam geometry, the centerline of the source is positioned 38.139 mm from the center of the detector.

p0.x, p0.y: coordinates of the center of the image on the detector.
Phi (φ): rotation angle of the detector relative to the x-axis.
Eta (η): rotation angle of the detector relative to the y-axis.
Theta (θ): rotation angle of the gantry.

The parameters in the geometry.txt file are currently fixed for testing with SOD = 410 mm and SDD = 660 mm, and the other variables have not been used.

Here is the whole LEAP script:

import sys
import os
import time
import numpy as np
import napari
import imageio
from leapctype import *
leapct = tomographicModels()

# Set the folder name where the data was downloaded
dataPath = r'C:\Users\mj\Desktop\geo_to_txt\FSSR_proj_x16'

# Read geometry file

# Specify the number of detector columns which is used below
# Scale the number of angles and the detector pixel size with N
# Set the number of detector rows
# Parameters setup based on bin_mode
bin_mode = False  # You can change this to False if binning is not desired

# Original dimensions and parameters
numAngles = 753
numRows_orig = 1628
numCols_orig = 1500
pixelSize_orig = 0.098  # original pixel size in mm
shift_distance = 38.139  # shift distance in mm
start_index = 43

if bin_mode:
    # Binning factor (2x2 binning implies reduction by a factor of 2)
    bin_factor = 2

    # Adjusted dimensions and pixel size for binned mode
    numRows = numRows_orig // bin_factor
    numCols = numCols_orig // bin_factor
    pixelSize = pixelSize_orig * bin_factor  # new pixel size is the original times the binning factor

    # Recalculate centers based on new dimensions and pixel size
    centerRow = 0.5 * (numRows - 1) - (shift_distance / pixelSize)
    centerCol = 0.5 * (numCols - 1) - (shift_distance / pixelSize)
else:
    # No binning: use original parameters
    numRows = numRows_orig
    numCols = numCols_orig
    pixelSize = pixelSize_orig

    # Calculate center using original dimensions and pixel size
    centerRow = 0.5 * (numRows_orig - 1) - (shift_distance / pixelSize_orig)
    centerCol = 0.5 * (numCols_orig - 1) - (shift_distance / pixelSize_orig)

# Set the scanner geometry
leapct.set_conebeam(numAngles-start_index, numRows, numCols, pixelSize, pixelSize, centerRow, centerCol, leapct.setAngleArray(numAngles-start_index, 360.0), 410, 660)
# Set the offsetScan flag to True
leapct.set_offsetScan(True)
# Set LEAP CT volume parameters
leapct.set_default_volume()
#leapct.set_volume(501, 501, 501, 0.1, 0.1)
leapct.print_parameters()
#leapct.sketch_system()

# Allocate space for the projections and the volume
g = leapct.allocateProjections()
f = leapct.allocateVolume()

# Read data
dtype = np.uint16  # 16 unsigned integer

file_list = [file for file in os.listdir(dataPath) if file.endswith('.raw')]
file_list.sort()

for index, filename in enumerate(file_list[start_index:]):  # Starts from the 43rd element
    file_path = os.path.join(dataPath, filename)
    with open(file_path, 'rb') as file:

        img_data = np.fromfile(file, dtype=dtype)
        if bin_mode:
            g[index, :, :] = img_data.reshape(numRows_orig//2, 2, numCols_orig//2, 2).mean(axis=(1, 3))  # Adjust index to maintain correct position in 'g'
        else:
            g[index, :, :] = img_data.reshape((numRows_orig, numCols_orig))

print("Stack shape:", g.shape)

parentPath = os.path.dirname(dataPath)
# airmap
file_path = os.path.join(parentPath, 'airmap.raw')
with open(file_path, 'rb') as file:
    img_data = np.fromfile(file, dtype=dtype)
    if bin_mode:
        airmap = img_data.reshape(numRows_orig // 2, 2, numCols_orig // 2, 2).mean(axis=(1, 3))
    else:
        airmap = img_data.reshape((numRows_orig, numCols_orig))

# Perform Flat Fielding
print('Flat Fielding...')
g = g / airmap
eps = 1e-10
g = -np.log(g+eps, dtype = np.float32)

#g = np.transpose(g, (0,2,1))
#g = np.flip(g,axis=0)
g = np.ascontiguousarray(g, dtype=np.float32)

leapct.display(g)
print('FBP reconstruction...')
startTime = time.time()
leapct.FBP(g,f)
print('Reconstruction Elapsed Time: ' + str(time.time()-startTime))

# Display result with napari
leapct.display(f)
#quit()

**Comment by kylechampley** [comment]
Thanks for the code.  I was able to make some improvements.  I fixed some more small bugs in the code, so please use the code in the [champley_dev](https://github.com/LLNL/LEAP/tree/champley_dev) branch until I merge in into the main branch this weekend.  The main two things I changes in the processing were:

1) Change the direction of the rotation.  Instead of an angular range of 360.0, just put -360.0.

2) Crop off the border of the projection images which contain bad pixels.  With the binned data, I did it like this:
g = leapct.crop_projections([2, leapct.get_numRows()-3], [2, leapct.get_numCols()-3], g)

With those changes, here is what I got.
![image](https://github.com/LLNL/LEAP/assets/84085392/20575d3c-bbe3-4132-8d91-0e9848a4d53a)

With those changes, it is still not a great result, but I noticed in the geometry file you posted that from projection-to-projection there seemed to be a lot of variation in the geometry.  You'll need to use LEAP's "modular-beam" geometry and specify all those parameters.  I did not know how to interpret all those parameters and information from some of the measured projections seemed to be missing from this file, so I couldn't try this myself.

**Comment by kylechampley** [comment]
Oh, one more thing.  Strictly speaking, this data cannot be properly reconstructed with the "offset scan" strategy because many of the projections are truncated on both sides.  Offset scan implies that the projections are only truncated on one side.  Yes, this is true for most of your projections, but there are enough projections that violate this, so you'll still get some artifacts.  Regardless, I think the next thing you need to do is use the modular-beam geometry as I discussed in my last post.

**Comment by ProjX0** [comment]
I first downloaded the code from the champley_dev branch, deleted the existing version, and reinstalled it.

I then made the changes as you suggested:

1. Change the direction of the rotation. Instead of an angular range of 360.0, just put -360.0.
leapct.set_conebeam(numAngles-start_index, numRows, numCols, pixelSize, pixelSize, centerRow, centerCol, leapct.setAngleArray(numAngles-start_index, -360.0), 410, 660)

However, I am still encountering problems. Is there something I missed?
![2024-05-16 08;38;56](https://github.com/LLNL/LEAP/assets/78583623/a7e627fe-bf4c-4bf9-a47d-fe717d5fd89b)

For reference, the whole LEAP script is as follows:
![image](https://github.com/LLNL/LEAP/assets/78583623/efd7a621-65d6-4e63-9017-a22c1a5c3b56)
![image](https://github.com/LLNL/LEAP/assets/78583623/d82f902e-adfc-42ff-8357-c7ba0ac2f431)

If this works, I will thoroughly examine the projection data and geometry information, and then attempt it using the modular-beam geometry. Thank you.

**Comment by ProjX0** [comment]
I apologize, but I entered the start_index incorrectly. With start_index = 47, the measured projection matches the information in geometry.txt. Can these parameters be applied to LEAP's "modular-beam" geometry?

**Comment by kylechampley** [comment]
Oh, I forgot.  I had to modify the detector shift amounts.  I used the following:
shift_distance_col = -47.138 # mm
shift_distance_row = -38.139 # mm

I am also concerned that you are still using an older version of LEAP.  To check the LEAP version run the following command:
leapct.about()
It should say version 1.11

**Comment by ProjX0** [comment]
The versions were different. Everything is working fine now that I matched the version to 1.11. Thank you very much. 
By the way, could you please explain how you estimated shift_distance_col and shift_distance_row?

**Comment by kylechampley** [comment]
Oh, wait, I just realized that centerCol and centerRow can be calculated from your geometry file like this:
centerCol = p0.x/pitch
centerRow = numRows - 1 - p0.y/pitch

Once I used these parameters, I got even better results.

**Comment by ProjX0** [comment]
thank you very much. It's working well now. 
I am trying to improve the image by reconstructing it using my geometry files for each projection.
May I ask you questions anytime if I have more inquiries?

**Comment by kylechampley** [comment]
I actually got a cudaMalloc error when I tried this.  Turns out this was caused by LEAP trying to allocate data with a negative number of elements.  I fixed this bug and pushed the changes.

OK, so the real issue here is that you need to do the following:
leapct.set_volume(750, 750, 450, 0.2, 0.2, 0.0, 0.0, -47.274899)

Note that the z=0 plane is defined by the centerRow parameter.  Since your centerRow parameter is far from numRows/2, your field of view is not centered around zero, it is centered around z=-47.274899, so you need to shift your volume to be centered in the field of view.  One way to automate this is the following
leapct.set_default_volume()
leapct.set_volume(750, 750, 450, 0.2, 0.2, 0.0, 0.0, leapct.get_offsetZ())

And one more thing.  To get rid of that bright ring around your reconstruction, add the following line to your script:
leapct.set_truncatedScan(True)

**Comment by kylechampley** [comment]
Thanks @[ProjX0](https://github.com/ProjX0) and @[hws203](https://github.com/hws203) for this discussion.  It has helped me find and fix several bugs in LEAP, making this toolbox better.  If you find LEAP useful, please consider giving it a "Star" by clicking the star icon on the LEAP main page.  Stars increase the visibility of LEAP, which brings in more users, which increases the chance of people reporting bugs such as yourselves, which helps improve LEAP for myself and everyone else who uses it.

**Comment by ProjX0** [comment]
Of course. I clicked "Star" because it is such a useful toolkit.

You mentioned two methods regarding the offset Z as follows:
1. leapct.set_volume(750, 750, 450, 0.2, 0.2, 0.0, 0.0, -47.274899)
2.leapct.set_default_volume()
    leapct.set_volume(750, 750, 450, 0.2, 0.2, 0.0, 0.0, leapct.get_offsetZ())

I have entered these into the code, but the output still appears blurry, as shown in the image below.
![image](https://github.com/LLNL/LEAP/assets/78583623/a073e859-e9fc-4a4f-bab1-7f5b3d46ce83)

P.S. The method to solve the truncation artifact, leapct.set_truncatedScan(True), works well. Thank you.

**Comment by kylechampley** [comment]
Are you using the latest code?  I just fixed this bug about 48 hours ago.  You can just pull from the main branch because I merged all changes to main.  Also I recommend cropping the data like this:

if bin_mode == True:
        g = leapct.crop_projections([3,numRows-4], [3,numCols-4], g)
    else:
        g = leapct.crop_projections([6,numRows-7], [6,numCols-7], g)

**Comment by hws203** [comment]
I have checked your v1.11 version about the offscan issue.
And I could see that there is still a FOV limit issue at the case of left side offscan with the  modification of "centerCols = 0.5*(numCols-1)-100" .

As you recommend if I add the leapct.set_diameterFOV(leapct.get_voxelWidth()*leapct.get_numX()), then there is no issue.

But I hope that it will work as like righ-side offscan example .

I added star mark too at your main page too.

Best regards.

**Comment by ProjX0** [comment]
@kylechampley Yes, I am using the latest code. Just in case, I downloaded the main code again and reinstalled it. 
I also tried cropping the data as you suggested, but the issue is still occurring.

**Comment by ProjX0** [comment]
Another issue is when using iterative reconstruction techniques in offset scans, the resulting image shows artifacts in the center as shown below. Is there a way to resolve this artifact?
![image](https://github.com/LLNL/LEAP/assets/78583623/a48c6e47-884b-4be4-b3f3-08228a036534)

**Comment by kylechampley** [comment]
Thanks for your patience.  I found and fixed another bug that hopefully solves your issue.  Apparently, I forgot to account for the extra memory used by texture memory and I was running out of memory.  Now I account for this and the data is chunking into smaller pieces.   The change just got pushed to the champley_dev branch; it should say version 1.12.  Please check this out and let me know if the issue is resolved.  By the way, what GPU are you using?

Now let's talk about iterative reconstruction.  That ring appears there because you are not converged; you need more iterations.  I can tell because your result looks blurry.  If you start with an FBP reconstruction this ring artifact won't be so strong because it'll be closer to convergence.

Also notice that the ring is the boundary of the edge of your detector as projected into the volume.  Inside the ring you have 360 degrees of projections and outside you have less than 360 degrees.  One way to mitigate these artifacts quicker with iterative reconstruction is to use an algorithm that accounts for this variable range in angular coverage.  SART, SIRT, and ASDPOCS due this naturally.  If you want to use LS, WLS, RLS, or RWLS make sure you add this argument: preconditioner='SQS'

Finally, I would like to remark about other issues with iterative reconstruction.  Iterative reconstruction can outperform FBP only when you have an accurate model.  If your geometry specification is off by too much or you have a lot of beam hardening, scatter, etc., iterative reconstruction might actually give a poorer result due to overfitting.  I would focus on getting all your geometry specifications into LEAP before doing iterative reconstruction.  You will also have issues with iterative reconstruction because of truncation artifacts.  To avoid these, make sure your reconstruction is reconstructing the whole object.  This includes turning off the windowing like this:
leapct.set_diameterFOV(2.0*leapct.get_voxelWidth()*leapct.get_numX())

Notice I added a 2.0 in the above calculation which will remove all the windowing.

Good luck!

**Comment by hws203** [comment]
I have checked the version 1.12 which included in  charmley-dev branch, and I can see the FOV-limit issue of off-scan has been cleared now.

**Comment by ProjX0** [comment]
@kylechampley 
first issue 
I am using an RTX 4090 with a single GPU. In version 1.12, I tested the FBP reconstruction with "bin_mode = false", and the results are shown below.

![image](https://github.com/LLNL/LEAP/assets/78583623/9d3edf5c-c827-4907-8b34-f05a23dd7e38)

The image blurring still occurred with the specific FOV settings, but when the FOV was set as on the right, the image blurring did not occur.

Second issue 
I tested the recommendations you gave previously for reducing ring artifacts and achieving better iterative reconstruction results.
The main modifications and additions to the code are as follows. 

bin_mode = True  ...
leapct.set_diameterFOV(2.0*leapct.get_voxelWidth()*leapct.get_numX()) 

f = leapct.FBP(g)
filters = filterSequence(2e2)
filters.append(TV(leapct, delta=0.01 / 100.0, p=1.0))
filters.append(histogramSparsity(leapct, mus=[0.0, 0.02], weight=0.00001))
leapct.RWLS(g, f, iteration_number, filters, preconditioner='SQS')

I used the RWLS reconstruction method and compared the number of iterations at 5, 10, and 50.

![image](https://github.com/LLNL/LEAP/assets/78583623/9e61cb42-0fe4-465e-b825-439e20118d0d)

As you can see from the results, the ring artifact inside became more pronounced as the number of iterations increased.
I think this seems to be a very normal tendency as you mentioned above.
So, rather than increasing the number of iterations or adjusting parameters related to reconstruction, it might be necessary to use another process to reduce the ring artifacts.

**Comment by hws203** [comment]
@kylechampley.    I found the almost some issue which named as "ramp-filter missing issue" by me. As you can see below image, after doFBP, the recon slice shows very blurred one as like there is no ramp-filer adapted during back-propagation.
![blurred_one](https://github.com/LLNL/LEAP/assets/73321363/912c7d7a-51f2-40fc-9280-977ff2e843a8)

And I attached my test script too. For your side test, I shared my image files(https://drive.google.com/file/d/1KvSFzIEzhvaSmuOSkTGAsPNymWqwTm0I/view?usp=sharing).
Please check this case.
From  Jeff.

**Comment by hws203** [comment]
import sys
import os
import time
import cv2
import numpy as np
from leapctype import *
leapct = tomographicModels()

# Specify the number of detector columns which is used below
# Scale the number of angles and the detector pixel size with N
numCols = 2404
numAngles = 360
pixelSize = 0.1

# Set the number of detector rows
numRows = 2196
#numRows = 1
# Set the central column and row indices
# Here we will start with a detector that
# is not centered on the optical axis
centerRow = 0.5*(numRows-1)
centerCol = 1223.5#0.5*(numCols-1)
# Make this modular-beam geometry just like a cone-beam dataset
# so let's define sod and sdd when defining our geometry
# In general, if your data fits into one of the standard geometry types,
# such as, parallel-, fan-, or cone-beam, then it is STRONGLY recommended
# that you use the standard type.
# The modular-beam projectors are not as fast and not as accurate
sod = 270.
sdd = 773.

# Set the scanner geometry
sourcePositions = np.ascontiguousarray(np.zeros((numAngles,3)).astype(np.float32), dtype=np.float32)
moduleCenters = np.ascontiguousarray(np.zeros((numAngles,3)).astype(np.float32), dtype=np.float32)
colVectors = np.ascontiguousarray(np.zeros((numAngles,3)).astype(np.float32), dtype=np.float32)
rowVectors = np.ascontiguousarray(np.zeros((numAngles,3)).astype(np.float32), dtype=np.float32)

T_phi = 2.0*np.pi/float(numAngles)
for n in range(numAngles):
    phi = n*T_phi-0.5*np.pi
    
    sourcePositions[n,0] = sod*np.cos(phi)
    sourcePositions[n,1] = sod*np.sin(phi)
    
    moduleCenters[n,0] = (sod-sdd)*np.cos(phi)
    moduleCenters[n,1] = (sod-sdd)*np.sin(phi)
    
    rowVectors[n,2] = 1.0
    theta = 0.0*np.pi/180.
    colVectors[n,0] = -np.sin(phi+theta)
    colVectors[n,1] = np.cos(phi+theta)

leapct.set_modularbeam(numAngles, numRows, numCols, pixelSize, pixelSize, sourcePositions, moduleCenters, rowVectors, colVectors)

# Set the volume parameters
#leapct.set_default_volume()
leapct.set_volume(1000, 1000, 1, 0.0549, 0.0549, 0, 0, 0)
# The next line is optional.  It sets the diameter of the circular field of view mask on the reconstruction volume
#leapct.set_diameterFOV(leapct.get_numX()*leapct.get_voxelWidth())

# Trouble-Shooting Functions
leapct.print_parameters()
#leapct.sketch_system(0)
#quit()
# Allocate space for the projections and the volume
g = leapct.allocateProjections()
f = leapct.allocateVolume()

# Specify simplified FORBILD head phantom
# One could easily do this in Python, but Python is soooooo slow for these types of operations,
# so we implemented this feature with multi-threaded C++
#leapct.set_FORBILD(f,True)
#leapct.display(f)
#g[:]=0.0
#leapct.set_gpu(0)
startTime = time.time()  
for n in range(g.shape[0]):
    buf = "./imgdong/name_%04d.tif" % (n)
    img =cv2.imread(buf,0)
    #img = cv2.resize(img, dsize=(0,0), fx=0.5,fy=0.5)
    img=cv2.flip(img,1) 
    #print(img.dtype)
    f_image = np.float32(img)
    f_image = f_image / 255.0 
    f_image = 1.0- f_image
    #y = np.expand_dims(f_image, axis=0)
    #print(g.shape)
    g[n, :, :] =f_image
    #cv2.imshow('img', f_image)
    #cv2.waitKey(10)
print('Reading time: ' + str(time.time()-startTime))
#I_0=50000
#g[:] = -np.log((I_0*np.exp(-g))/I_0)
# "Simulate" projection data
#startTime = time.time()
#leapct.project(g,f)
#print('Forward Projection Elapsed Time: ' + str(time.time()-startTime))
#leapct.display(g)
#quit()
leapct.set_conebeam(numAngles, numRows, numCols, pixelSize, pixelSize, centerRow, centerCol, leapct.setAngleArray(numAngles, 360.0), sod, sdd)
leapct.find_centerCol(g)
#leapct.set_centerCol(leapct.get_centerCol())



# Reset the volume array to zero, otherwise iterative reconstruction algorithm will start their iterations
# with the true result which is cheating
f[:] = 0.0
leapct.set_diameterFOV(1.0*leapct.get_voxelWidth()*leapct.get_numX())
# Reconstruct the data
startTime = time.time()
#leapct.set_rampFilter(10)
#leapct.set_truncatedScan(True)
#leapct.backproject(g,f)
leapct.FBP(g,f, True)

print('Reconst Elapsed Time: ' + str(time.time()-startTime))


# Display the result with napari
#leapct.display(f)


#''' Compare to cone-beam
#ct2 = tomographicModels()
#ct2.set_conebeam(numAngles, numRows, numCols, pixelSize, pixelSize, 0.5*(numRows-1), 0.5*(numCols-1), leapct.setAngleArray(numAngles, 360.0), sod, sdd)
#ct2.set_default_volume()
#ct2.set_volume(1000, 1000, 1000, 0.0349, 0.0349, 0, 0, 0)
#f_cone = ct2.allocateVolume()
#ct2.FBP(g,f_cone)
#leapct.display(f_cone)

leapct.display(f)
quit()
#'''

**Comment by hws203** [comment]
![script1](https://github.com/LLNL/LEAP/assets/73321363/5e32b396-88a0-42ae-ae6b-1ca5f504a36c)
![script2](https://github.com/LLNL/LEAP/assets/73321363/3d8e9252-c220-400b-8ef2-e8fa662593ea)

**Comment by kylechampley** [comment]
I just cannot reproduce those blurry results that you guys are getting.  I've tried both of your data sets on two different computers (Windows with 2 1080Ti GPUs and Linux with 2 4090 GPUs).  All I can say is run the leapct.about() command and make sure it says version 1.12.  I know you said you checked this, but I am at a loss as to the cause of those blurry results.

@hws203 I don't understand why you included the modular-beam stuff in that script.  I skipped all of that.  The reconstruction didn't look great, but it definitely didn't look blurry like what you posted.  There is likely something wrong with the geometry specification.  Anyway, here is what I got.
![image](https://github.com/LLNL/LEAP/assets/84085392/300e380f-e6b3-4ea8-a87e-9ba0b477a432)


@ProjX0 I would not include the histogram sparsity regularizer.  This filter is only for severely ill-posed reconstructions like limited angle or few-view.  In addition, the values you give it do not agree with the LAC values in your object, so it will likely give very strange results with the parameters you specified.  If I were you, I would focus on getting all your geometry parameters correct before I started working on iterative reconstruction.  From the looks of your geometry file, your system has a fair amount of variability from projection to projection.

Oh, and be careful when you call them "ring artifacts".  I agree that the artifact is a ring, but "ring artifacts" is a specific term in CT that is caused by detector pixel-to-pixel gain variations that cause several ring artifacts in reconstructions.

**Comment by ProjX0** [comment]
Thank you so much for the detailed and great feedback.

As you pointed out in https://github.com/LLNL/LEAP/issues/35#issuecomment-2115606743, when centerCol and centerRow are not the center, where should I make changes in the following modularbeam code?

T_phi = 2.0*np.pi/float(numAngles)
for n in range(numAngles):
    phi = n*T_phi-0.5*np.pi
    
    sourcePositions[n,0] = sod*np.cos(phi)
    sourcePositions[n,1] = sod*np.sin(phi)
    
    moduleCenters[n,0] = (sod-sdd)*np.cos(phi)
    moduleCenters[n,1] = (sod-sdd)*np.sin(phi)
    
    rowVectors[n,2] = 1.0
    
    colVectors[n,0] = -np.sin(phi)
    colVectors[n,1] = np.cos(phi)

leapct.set_modularbeam(numAngles, numRows, numCols, pixelSize, pixelSize, sourcePositions, moduleCenters, rowVectors, colVectors)

**Comment by hws203** [comment]
I found the key function for making this blurry result, that is the custom volume setting function which is 'leapct.set_volume()'.
If I use leapct.set_default_volume() function, then there is no such blurry result.
 I can not understand why this happens with leapct.set_volume() function. Please explain this reason.

Below is the reconed slice with leapct.set_default_volume().
![default_volume](https://github.com/LLNL/LEAP/assets/73321363/c65f37bc-e813-458c-b0f2-bbad128d6b4b)
Below is my new script.
![script_02](https://github.com/LLNL/LEAP/assets/73321363/7a6585b8-2686-48dd-9802-9c3b85799ad8)

**Comment by ProjX0** [comment]
@hws203 In my cases, I've encountered an issue with my geometry and data where the image blurs when using leapct.set_default_volume(). Despite asking @kylechampley several times, we haven't been able to identify the problem. I'm still at a loss about what's causing this.

**Comment by hws203** [comment]
@ProjX0  I guess that this blurry issue is also related to the allocated memory size of GPU.  But I can not identify it clearly. 
But at my case study, there might be  some clue for this issue.

**Comment by kylechampley** [comment]
The problem with this bug is that I cannot reproduce it.  I have tried on two different computers and on both computers I get the expected result, no matter how I set the volume.

There is nothing magical about the set_default_volume function.  For cone-beam it sets the voxel size like this:
voxelWidth = sod / sdd * pixelWidth
voxelHeight = sod / sdd * pixelHeight
and then it sets the number of voxels and offsetZ so that the volume fills the field of view and is centered in the field of view.

The likely issue is that there is some failure in the CUDA functions that do the filtering and it fails silently (i.e., no error message is printed to the screen).  The failure is likely a malloc error which would explain why it seems to depend on the size of the volume.

I will work on catching all possible errors in the filtering functions of LEAP and push a new version in about 12 hours from now.  I'll let you know when it is ready.

**Comment by hws203** [comment]
I checked your logged version from champley-branch, but unfortunately, there is no error message. I will check it more Today.
![screen](https://github.com/LLNL/LEAP/assets/73321363/4475f5cd-a822-44b2-8606-690894083b0c)
![scrip03](https://github.com/LLNL/LEAP/assets/73321363/413a4dc7-45f9-4d31-b93c-62906599c844)

**Comment by hws203** [comment]
I got some clue after changing the leapct.set_volume() to leapct.set_default_volume(), there are some logging about slice generation at GPU.
So, I guess that at the blurry result case, your code does not reach this line code. 
Please check this point and add more log if you need. And let me try to check it again.
![GPU_log01](https://github.com/LLNL/LEAP/assets/73321363/bfe7bf3e-ea13-4592-b608-98120345c19d)

**Comment by hws203** [comment]
@kylechampley leap.find_centerCol() function is also affected by this volume size, this find_centerCol() function also works correctly only at the case of default_volume size.  Please check this one too.

**Comment by kylechampley** [comment]
The volume specification (e.g., volume size) has absolutely no impact on the output of leapct.find_center().

But the output of leapct.find_center() will affect leapct.set_default_volume().  And it definitely should.  The placement of your detector affects the size of the field of view that you can reconstruction.  Thus, different values of centerCol will make the volume specified by leapct.set_default_volume() have different values.

This is all intentional.

**Comment by ProjX0** [comment]
Thank you once again for your kind and prompt response.

I conducted tests on three cases. In cases (1) and (3), when I set the volume and FOV as per the code inserted in the figure, there was no image blurring. However, in case (2), when the settings were applied, image blurring occurred, and no log messages were generated. (For reference, the right side of the figure shows the log messages output for each case.)

![image](https://github.com/LLNL/LEAP/assets/78583623/4a281316-bc9b-459f-b79e-d514ea8719b6)

I have sent the code I used via email.

**Comment by hws203** [comment]
I found that the cudaFFT library makes this issue. So if I build Leap v1.12 without  "__INCLUDE_CUFFT" option, then there is no such blurry issue.  I guess that cudaFFT usage is not matched to their intent.

**Comment by kylechampley** [comment]
OK, I finally fixed the bug!  Again, please pull from the [champley_dev](https://github.com/LLNL/LEAP/tree/champley_dev) branch.

@hws203 I do not recommend turning off CUFFT.  You will lose some features in LEAP and things will go slower.

The reason why the ramp filter was not being applied was that I was launching a CUDA kernel with a block size that was too big.  I always test LEAP on machines with multiple GPUs and with multiple GPUs the job gets divided across all the GPUs and then it never happened that I used a block size that was too big.  To reproduce the effect you guys saw, I had to tell LEAP to use just one GPU.

Also, you guys sometimes did not encounter this bug because LEAP was dividing the job into smaller pieces when LEAP determined that you'd run out of GPU memory if it wasn't split up.

Regardless, I am confident that this is fixed.

**Comment by hws203** [comment]
Ramp-filter with CudaFFT is now working well at your new champly-dev version.
![ramp_filter](https://github.com/LLNL/LEAP/assets/73321363/a4f41b08-3d3c-4a96-9018-391bc27ae16f)

**Comment by ProjX0** [comment]
I also did not experience any image blurring with my setup. Thank you.

However, while performing modularbeam using my geometry file, I encountered another issue during testing. I discovered an issue where the code does not stop at leapct.FBP(g, f) (resulting in infinite loading). Upon checking the Task Manager, I noticed that the CUDA operations were not active.

I have sent you detailed information about this problem via email.
You can check the most recent email I sent for detailed information about this problem.

**Comment by kylechampley** [comment]
Yes, I saw your email.  I solved that problem and a few others in the script you sent me, but the reconstruction still looks a bit blurry.  I'll respond to you by email in a day or two with my corrections.

I am closing this issue because I believe the offset scan issues have been resolved in LEAP.
